// Project the scraper's normalized SQLite (cen-news-notifications/data/cen.db)
// into a flat seed for cen-sql — the Phase-1 "seed by import" path. Reads the
// sibling repo's cen.db read-only and writes cen-seed.sql (full replace:
// DELETE then INSERT), which you load into cen-sql with:
//
//   node scripts/cen-project.mjs [path/to/cen.db]
//   wrangler d1 execute cen-sql --local  --file=cen-seed.sql
//   wrangler d1 execute cen-sql --remote --file=cen-seed.sql
//
// Only public tournament data crosses over (tournaments / events / standings +
// entrant names) — no emails, verification codes, or other PII. The output is
// gitignored; it's a local import artifact, never committed.

import { DatabaseSync } from "node:sqlite";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";

const DEFAULT_DB = resolve(
  process.cwd(),
  "../cen-news-notifications/data/cen.db",
);
const dbPath = process.argv[2] ? resolve(process.argv[2]) : DEFAULT_DB;
const outPath = resolve(process.cwd(), "cen-seed.sql");

/** SQLite string literal, doubling single quotes; NULL for null/undefined. */
const q = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v == null || v === "" ? "NULL" : String(Number(v)));

/** cen stores 'YYYY.MM.DD HH:MM' (UTC) -> epoch ms, or NULL. */
function dateMs(s) {
  if (!s) return null;
  const m = /^(\d{4})\.(\d{2})\.(\d{2}) (\d{2}):(\d{2})/.exec(String(s).trim());
  if (!m) return null;
  const [, Y, Mo, D, H, Mi] = m;
  return Date.UTC(+Y, +Mo - 1, +D, +H, +Mi);
}

let db;
try {
  db = new DatabaseSync(dbPath, { readOnly: true });
} catch (e) {
  console.error(`Could not open cen.db at ${dbPath}\n${e}`);
  process.exit(1);
}

const tournaments = db
  .prepare(
    `SELECT t.sources_id AS source,
            t.tournaments_source_tournament_id AS sid,
            t.tournaments_name AS name,
            t.tournaments_slug AS slug,
            t.tournaments_start_at AS start_at,
            t.tournaments_end_at AS end_at,
            t.tournaments_num_attendees AS num_attendees,
            t.tournaments_city AS city,
            t.tournaments_country AS country,
            t.tournaments_url AS url,
            COALESCE(cg.canonical_games_name, g.games_name) AS game
     FROM tournaments t
     JOIN games g ON g.games_id = t.games_id
     LEFT JOIN canonical_games cg ON cg.canonical_games_id = g.canonical_games_id`,
  )
  .all();

const events = db
  .prepare(
    `SELECT t.sources_id AS source,
            t.tournaments_source_tournament_id AS sid,
            e.events_source_event_id AS eid,
            e.events_name AS name,
            e.events_state AS state,
            e.events_num_entrants AS num_entrants
     FROM events e
     JOIN tournaments t ON t.tournaments_id = e.tournaments_id`,
  )
  .all();

const standings = db
  .prepare(
    `SELECT t.sources_id AS source,
            t.tournaments_source_tournament_id AS sid,
            ev.events_source_event_id AS eid,
            en.entrants_id AS entrant_id,
            en.entrants_name AS entrant_name,
            en.entrants_is_team AS is_team,
            s.standings_placement AS placement
     FROM standings s
     JOIN entrants en ON en.entrants_id = s.entrants_id
     JOIN events ev ON ev.events_id = en.events_id
     JOIN tournaments t ON t.tournaments_id = ev.tournaments_id`,
  )
  .all();

db.close();

const tId = (r) => `${r.source}:${r.sid}`;
const eId = (r) => `${r.source}:${r.sid}:${r.eid}`;
const now = Date.now();

const lines = [
  "-- Generated by scripts/cen-project.mjs — do not edit by hand.",
  "DELETE FROM ext_standings;",
  "DELETE FROM ext_events;",
  "DELETE FROM ext_tournaments;",
];

for (const r of tournaments) {
  lines.push(
    "INSERT INTO ext_tournaments (id, source, source_tournament_id, name, slug, game, start_at, end_at, num_attendees, city, country, url, updated_at) VALUES (" +
      [
        q(tId(r)),
        q(r.source),
        q(r.sid),
        q(r.name ?? "Untitled"),
        q(r.slug),
        q(r.game),
        n(dateMs(r.start_at)),
        n(dateMs(r.end_at)),
        n(r.num_attendees),
        q(r.city),
        q(r.country),
        q(r.url),
        n(now),
      ].join(", ") +
      ");",
  );
}

for (const r of events) {
  lines.push(
    "INSERT INTO ext_events (id, tournament_id, source_event_id, name, state, num_entrants) VALUES (" +
      [q(eId(r)), q(tId(r)), q(r.eid), q(r.name), q(r.state), n(r.num_entrants)].join(", ") +
      ");",
  );
}

for (const r of standings) {
  lines.push(
    "INSERT INTO ext_standings (id, event_id, entrant_name, is_team, placement) VALUES (" +
      [
        q(`${eId(r)}:${r.entrant_id}`),
        q(eId(r)),
        q(r.entrant_name ?? "—"),
        r.is_team ? "1" : "0",
        n(r.placement),
      ].join(", ") +
      ");",
  );
}

writeFileSync(outPath, lines.join("\n") + "\n", "utf8");
console.log(
  `Wrote ${outPath}\n  ${tournaments.length} tournaments, ${events.length} events, ${standings.length} standings.`,
);
